#!/usr/bin/env bash
#Configure HAProxy to be able to accept requests on port tcp/80 and redirect them to the we>sudo apt update -y
sudo apt install haproxy -y
config=\
"backend my_servers
        balance roundrobin
        server 5493-web-01 18.215.168.54
        server 5493-web-02 54.167.28.226
frontend haproxy_inbound
        bind *:80
        default_backend my_servers
        mode http
"

sudo chown -R "$USER":"$USER" /etc/default/haproxy
sudo chown -R "$USER":"$USER" /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "$config" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
